#!/usr/bin/env bash

# Activate virtual environment
this_dir="$(dirname "$0")"
root_dir="$this_dir/.."
source "$root_dir/venv/bin/activate"

cd "$root_dir/client"
npm run start &
pid=$!

echo "client server's pid is $pid"

cd ..
export FLASK_APP="$root_dir/app.py"
export FLASK_ENV="development"
export PORT=9999
flask run --port="$PORT"

# When back-end server is interrupted, front-end server should be as well
kill -15 $pid