#!/usr/bin/env bash

# Activate virtual environment
this_dir="$(dirname "$0")"
root_dir="$this_dir/.."
source "$root_dir/venv/bin/activate"

(cd "$root_dir/client" && npm run build) || exit 1
FLASK_APP="$root_dir/app.py"
export FLASK_ENV="production"
export PORT=7777
python3 "$FLASK_APP"